//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab5.Properties.stringFR", typeof(stringFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez vous coutinuez? Y/N.
        /// </summary>
        internal static string ContinuePrompt {
            get {
                return ResourceManager.GetString("ContinuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez rien entrer.
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Une erreure s&apos;est produite lors de la rédaction de: {ex.Message}&quot;.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;le fichier &apos;{filename}&apos; n&apos;existe pas&quot;.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez enter le chemin d&apos;accès du fichier, ansi que de son nom.
        /// </summary>
        internal static string FilePathRequest {
            get {
                return ResourceManager.GetString("FilePathRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;option entée n&apos;est pas reconnue.
        /// </summary>
        internal static string NotValidOption {
            get {
                return ResourceManager.GetString("NotValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;option entée n&apos;est pas reconnue. fichier: F - fichier / M - manuel.
        /// </summary>
        internal static string NotValidOptionLoopBack {
            get {
                return ResourceManager.GetString("NotValidOptionLoopBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez mot(s) brouillé(s) manuellement ou sous forme de fichier: F - fichier / M - manuel.
        /// </summary>
        internal static string OptionRequest {
            get {
                return ResourceManager.GetString("OptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminaison du programme.
        /// </summary>
        internal static string ProgramTermination {
            get {
                return ResourceManager.GetString("ProgramTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le(s) mot(s) manuellement (séparé(s) par des virgules si plusieurs) :.
        /// </summary>
        internal static string WordEntryRequest {
            get {
                return ResourceManager.GetString("WordEntryRequest", resourceCulture);
            }
        }
    }
}
