//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab5.Properties.stringEN", typeof(stringEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue? Y/N.
        /// </summary>
        internal static string ContinuePrompt {
            get {
                return ResourceManager.GetString("ContinuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Scrambled word: {matchedWord.ScrambledWord}, Unscrambled word: {matchedWord.Word}&quot;.
        /// </summary>
        internal static string DisplayMatchedUnscrambledWords {
            get {
                return ResourceManager.GetString("DisplayMatchedUnscrambledWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty entry.
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Error reading the file: {ex.Message}&quot;.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;the file &apos;{filename}&apos; does not exist.&quot;.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter full path including the file name:.
        /// </summary>
        internal static string FilePathRequest {
            get {
                return ResourceManager.GetString("FilePathRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue in English or French? EN/FR.
        /// </summary>
        internal static string LanguangeOption {
            get {
                return ResourceManager.GetString("LanguangeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched words:.
        /// </summary>
        internal static string MatchedWordsFound {
            get {
                return ResourceManager.GetString("MatchedWordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matched words found..
        /// </summary>
        internal static string NoMatchedWordsFound {
            get {
                return ResourceManager.GetString("NoMatchedWordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered option was not recognized..
        /// </summary>
        internal static string NotValidOption {
            get {
                return ResourceManager.GetString("NotValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered option was not recognized. Enter &apos;F&apos; for file or &apos;M&apos; for manual..
        /// </summary>
        internal static string NotValidOptionLoopBack {
            get {
                return ResourceManager.GetString("NotValidOptionLoopBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter scrambled word(s) manually or as a file: F - file / M - manual.
        /// </summary>
        internal static string OptionRequest {
            get {
                return ResourceManager.GetString("OptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program will be terminated..
        /// </summary>
        internal static string ProgramTermination {
            get {
                return ResourceManager.GetString("ProgramTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter word(s) manually (separated by commas if multiple):.
        /// </summary>
        internal static string WordEntryRequest {
            get {
                return ResourceManager.GetString("WordEntryRequest", resourceCulture);
            }
        }
    }
}
